# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flicha-Driver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TiCKTOC-Driver
  

#pod 'TTSegmentedControl', '~>0.3'

#pod 'SideMenuController'
#pod 'IQKeyboardManagerSwift', '5.0.7'
#pod 'GooglePlaces', '3.0.3'
#pod 'GooglePlacePicker', '3.0.3'
#pod 'GoogleMaps'
#pod 'Alamofire', '4.6.0'
#pod 'NVActivityIndicatorView', '4.1.1'
#pod 'SDWebImage', '4.3.0'
#pod 'M13Checkbox', '3.2.2'
#pod 'Socket.IO-Client-Swift', '11.1.3'
#pod 'SRCountdownTimer'
#pod 'Crashlytics'
#pod 'ACProgressHUD-Swift'
#pod 'CreditCardForm', '0.1.7'
#pod 'CardIO'
#pod 'FormTextField', '2.0.0'
#pod 'FloatRatingView', '3.0'
#pod 'Firebase/Core'
#pod 'Firebase/Messaging'
#pod 'MarqueeLabel/Swift', '3.1.4'
#pod 'DropDown', '2.3.1'
#pod 'IQDropDownTextField'
#pod 'ACFloatingTextfield-Swift', '1.7'
#pod 'Crashlytics', '3.9.3'
#pod 'Fabric'
#pod 'GoogleAnalytics', '3.17.0'
#pod 'LGSideMenuController'


pod 'SideMenuController'
pod 'IQKeyboardManagerSwift'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'Alamofire'
pod 'NVActivityIndicatorView'
pod 'SDWebImage'
pod 'M13Checkbox'
pod 'Socket.IO-Client-Swift'
pod 'SRCountdownTimer'
pod 'Crashlytics'
pod 'ACProgressHUD-Swift'
pod 'CreditCardForm'
pod 'CardIO'
pod 'FormTextField'
pod 'FloatRatingView'
#pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Analytics'
pod 'MarqueeLabel/Swift'
pod 'DropDown'
pod 'IQDropDownTextField'
pod 'ACFloatingTextfield-Swift'
pod 'Crashlytics'
pod 'Fabric'
pod 'Kingfisher'
pod 'SwiftyJSON'
#pod 'GoogleAnalytics'
pod 'LGSideMenuController'

end
#    pod 'ActionSheetPicker-3.0'
#    pod 'LGSideMenuController'
#    pod 'SwiftyJSON'
#    pod 'IQKeyboardManagerSwift'
#    pod 'Alamofire'
#    pod 'Socket.IO-Client-Swift'
#    pod 'SwiftMessages'
#    pod 'SkyFloatingLabelTextField'
#    pod 'GoogleMaps'
#    pod 'GooglePlaces'
#    pod 'Charts'
#    pod 'NVActivityIndicatorView'
#    pod 'Kingfisher'
#    pod 'MarqueeLabel/Swift'
##    pod 'Firebase'
#    pod 'Firebase/Messaging'
#    pod 'Firebase/Analytics'
#    pod 'Fabric'
#    pod 'Crashlytics'
#    pod 'AnyFormatKit'
